<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>True</UseWPF>
        <ApplicationIcon>Icon.ico</ApplicationIcon>
        <Version>1.0.0</Version>
        <LangVersion>latest</LangVersion>
        <Title>Explorer Tab Lite</Title>
        <Authors>yangdongsheng</Authors>
        <Company>$(AssemblyName)</Company>
        <Description>Lightweight Explorer tab tool: Force new windows to tabs with file selection preserved.</Description>
        <SatelliteResourceLanguages>none</SatelliteResourceLanguages>
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ConfigureAwait.Fody" Version="3.3.2" PrivateAssets="all"/>
        <PackageReference Include="Fody" Version="6.9.2" PrivateAssets="all"/>
        <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="SHDocVw">
            <HintPath>lib\Interop.SHDocVw.dll</HintPath>
            <EmbedInteropTypes>true</EmbedInteropTypes>
        </Reference>
        <Reference Include="Shell32">
            <HintPath>lib\Interop.Shell32.dll</HintPath>
            <EmbedInteropTypes>true</EmbedInteropTypes>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <Resource Include="Icon.ico"/>
    </ItemGroup>

</Project>
